### ISSUE TITLE
The last release (2.0.4) broke the colon

### ISSUE THREAD

**Issue by Olit2000** [Magisk-Modules-Repo/exo2-font#5]
The last release (2.0.4) broke the colon again. It has once been solved #1

**Comment by P1N2O** [comment]
Temporarily reverted to old version.
Fix coming soon! All issues will be fixed shortly..

**Comment by just-Nob** [comment]
Have the same issue.

**Comment by Olit2000** [comment]
@P1N2O, could you please release the reverted version to the magisk repo? 
I'd suggest that you revert changes to the font file to v2.0.2 because that as far as I can remember the last working version

**Comment by P1N2O** [comment]
@Olit2000 Done. Hope it helps..

**Comment by Olit2000** [comment]
It does help. Thanks
